src/addmigrat/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace addmigrat.Models
{
    public class Location
    {
        public int LocationID { get; set; }
        public string Country { get; set; }
        public string Place { get; set; }
        public string State { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}

src/addmigrat/Controllers/LocationsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using addmigrat.Models;
using System;
using System.Collections.Generic;


namespace addmigrat.Controllers
{
    public class LocationsController : Controller
    {
        private ApplicationDbContext _context;

        public LocationsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Locations
        public IActionResult Index(string sortOrder,string SearchString,string place) 
        {
            ViewBag.countrySort = String.IsNullOrEmpty(sortOrder) ? "country_desc" : "";
            ViewBag.placeSort = sortOrder == "Place" ? "place_desc" : "Place";
            
            //drop down list populating
            var placelist = new List<String>();

            var places = from m in _context.Locations
                         orderby m.Place
                         select m.Place;

            placelist.AddRange(places);

            ViewBag.place = new SelectList(placelist);

            //search operations
            var locations = from m in _context.Locations
                         select m;

            if (!String.IsNullOrEmpty(SearchString) || !String.IsNullOrEmpty(place))
            {
                locations = locations.Where(s => (s.Country.Contains(SearchString)) && (s.Place == place));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    locations = locations.OrderByDescending(s => s.Country);
                    break;
                case "Place":
                    locations = locations.OrderBy(s => s.Place);
                    break;
                case "place_desc":
                    locations = locations.OrderByDescending(s => s.Place);
                    break;
                default:
                    locations = locations.OrderBy(s => s.Country);
                    break;
            }
           
            //int pageSize = 3;
            //int pageNumber = (page ?? 1);
            //return View(locations.ToPagedList(pageNumber, pageSize));

            return View(locations);
            //return View(_context.Locations.ToList());
        }


        // GET: Locations/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Location location = _context.Locations.Single(m => m.LocationID == id);
            if (location == null)
            {
                return HttpNotFound();
            }

            return View(location);
        }

        // GET: Locations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Location location)
        {
            if (ModelState.IsValid)
            {
                _context.Locations.Add(location);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Locations/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Location location = _context.Locations.Single(m => m.LocationID == id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Location location)
        {
            if (ModelState.IsValid)
            {
                _context.Update(location);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Location location = _context.Locations.Single(m => m.LocationID == id);
            if (location == null)
            {
                return HttpNotFound();
            }

            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Location location = _context.Locations.Single(m => m.LocationID == id);
            _context.Locations.Remove(location);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/addmigrat/Views/Locations/Create.cshtml
@model addmigrat.Models.Location

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Location</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Country" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Latitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Longitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Place" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="State" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/addmigrat/Views/Locations/Delete.cshtml
@model addmigrat.Models.Location

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Location</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/addmigrat/Views/Locations/Details.cshtml
@model addmigrat.Models.Location

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Location</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.LocationID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</p>

src/addmigrat/Views/Locations/Edit.cshtml
@model addmigrat.Models.Location

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Location</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="LocationID" />
        <div class="form-group">
            <label asp-for="Country" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Latitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Longitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Place" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="State" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/addmigrat/Views/Locations/Index.cshtml
@model IEnumerable<addmigrat.Models.Location>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
    @using (Html.BeginForm("Index","Locations",FormMethod.Get))
    {
    <p>
        Place: @Html.DropDownList("place")
        Country: @Html.TextBox("SearchString") <br /><br/>
        <input type="submit" class="btn btn-info" value="Search" />
    </p>
    }
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Country", "Index", new { sortOrder = ViewBag.countrySort })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Latitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Longitude)
        </th>
        <th>
            @Html.ActionLink("Place", "Index", new { sortOrder = ViewBag.placeSort })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th></th>
    </tr>
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Latitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Longitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Place)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.LocationID">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.LocationID">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.LocationID">Delete</a>
        </td>
    </tr>
}

</table>